table Dim_Hora
	lineageTag: be452976-17dd-4ed5-8d6c-3031241a862b

	column Hora
		dataType: dateTime
		formatString: Long Time
		lineageTag: cfc640fd-80f8-4d21-a26b-88b6879aff54
		summarizeBy: none
		sourceColumn: Hora

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Hora_Numero
		dataType: int64
		formatString: 0
		lineageTag: 21fc810d-824a-412e-a757-8aec7728b73e
		summarizeBy: none
		sourceColumn: Hora_Numero

		annotation SummarizationSetBy = Automatic

	column Minuto_Numero
		dataType: int64
		formatString: 0
		lineageTag: 2f64d106-ae60-4b2e-8259-6d9357f64fef
		summarizeBy: none
		sourceColumn: Minuto_Numero

		annotation SummarizationSetBy = Automatic

	column AM_PM
		dataType: string
		lineageTag: 604f2e50-28fa-45fe-82a7-a7891da742fd
		summarizeBy: none
		sourceColumn: AM_PM

		annotation SummarizationSetBy = Automatic

	column Hora_12
		dataType: int64
		formatString: 0
		lineageTag: 2266d075-1ca5-4e4f-ad39-9960d7e17907
		summarizeBy: none
		sourceColumn: Hora_12

		annotation SummarizationSetBy = Automatic

	column Hora_Formato
		dataType: string
		lineageTag: bd72d3cb-d11f-4031-b99a-4551b8a3e1d7
		summarizeBy: none
		sourceColumn: Hora_Formato

		annotation SummarizationSetBy = Automatic

	partition Dim_Hora = m
		mode: import
		source = ```
				let
				    // 1. Generamos la lista directamente en formato HORA (1440 minutos, avanzando de 1 en 1)
				    Origen = List.Times(#time(0, 0, 0), 1440, #duration(0, 0, 1, 0)),
				    
				    // 2. Convertimos a tabla forzando de inmediato que sea tipo 'time'
				    Tabla = Table.FromList(Origen, Splitter.SplitByNothing(), type table [Hora = time]),
				    
				    // 3. Extraemos Hora y Minuto (Números enteros)
				    AddHoraNum = Table.AddColumn(Tabla, "Hora_Numero", each Time.Hour([Hora]), Int64.Type),
				    AddMinNum = Table.AddColumn(AddHoraNum, "Minuto_Numero", each Time.Minute([Hora]), Int64.Type),
				    
				    // 4. Agregamos AM / PM
				    AddAMPM = Table.AddColumn(AddMinNum, "AM_PM", each if [Hora_Numero] < 12 then "AM" else "PM", type text),
				    
				    // 5. Formato de 12 horas (1 al 12)
				    AddHora12 = Table.AddColumn(AddAMPM, "Hora_12", each if [Hora_Numero] = 0 then 12 else if [Hora_Numero] > 12 then [Hora_Numero] - 12 else [Hora_Numero], Int64.Type),
				    
				    // 6. Etiqueta final visual (Ej: "02:30 PM")
				    AddEtiqueta = Table.AddColumn(AddHora12, "Hora_Formato", each Text.PadStart(Text.From([Hora_12]), 2, "0") & ":" & Text.PadStart(Text.From([Minuto_Numero]), 2, "0") & " " & [AM_PM], type text)
				in
				    AddEtiqueta
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

